//Auth
export const SET_AUTH_LOADER = 'SET_AUTH_LOADER';
export const SET_AUTH_DETAILS = 'SET_AUTH_DETAILS';
export const UPDATE_AUTH_DETAILS = 'UPDATE_AUTH_DETAILS';
export const CLEAR_AUTH_DETAILS = 'CLEAR_AUTH_DETAILS';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const UPDATE_AUTH_ERROR = 'UPDATE_AUTH_ERROR';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const SET_LOGIN_DETAILS = 'SET_LOGIN_DETAILS';
export const UPDATE_LOGIN_DETAILS = 'UPDATE_LOGIN_DETAILS';
export const CLEAR_LOGIN_DETAILS = 'CLEAR_LOGIN_DETAILS';
export const SET_SUBSCRIPTIONS_LIST = 'SET_SUBSCRIPTIONS_LIST';

// Reset password
export const SET_RESET_PASSWORD_DETAILS = 'SET_RESET_PASSWORD_DETAILS';
export const UPDATE_RESET_PASSWORD_DETAILS = 'UPDATE_RESET_PASSWORD_DETAILS';
export const CLEAR_RESET_PASSWORD_DETAILS = 'CLEAR_RESET_PASSWORD_DETAILS';


// Users
export const SET_ALL_USERS_LIST = 'SET_ALL_USERS_LIST';