/**
 * @desc Environment Variables
 */
export const DESIGN_HUDDLE_CLIENT_ID = process.env.DESIGN_HUDDLE_CLIENT_ID;
export const DESIGN_HUDDLE_CLIENT_SECRET = process.env.DESIGN_HUDDLE_CLIENT_SECRET_KEY;
export const FIREBASE_ADMIN_SDK_CERT = process.env.FIREBASE_ADMIN_SDK_CERT;
export const NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY;
export const NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
export const NEXT_PUBLIC_FIREBASE_PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
export const NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
export const NEXT_PUBLIC_FIREBASE_MESSAGIN_SENDER_ID = process.env.NEXT_PUBLIC_FIREBASE_MESSAGIN_SENDER_ID;
export const NEXT_PUBLIC_FIREBASE_APP_ID = process.env.NEXT_PUBLIC_FIREBASE_APP_ID;
export const NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID;
