const categoryList = [
  { label: 'Photo', value: 'Photo' },
  { label: 'Anime', value: 'Anime' }
];

const imageExportOptions = [
  { label: 'jpg', value: 'jpg' },
  { label: 'png', value: 'png' },
  { label: 'pdf', value: 'pdf' },
  { label: 'gif', value: 'gif' },
  { label: 'mp4', value: 'mp4' }
];

const currencySymbols = [
  { code: 'AED', symbol: '\u062f.\u0625;', name: 'UAE dirham' },
  { code: 'AFN', symbol: 'Afs', name: 'Afghan afghani' },
  { code: 'ALL', symbol: 'L', name: 'Albanian lek' },
  { code: 'AMD', symbol: 'AMD', name: 'Armenian dram' },
  { code: 'ANG', symbol: 'NA\u0192', name: 'Netherlands Antillean gulden' },
  { code: 'AOA', symbol: 'Kz', name: 'Angolan kwanza' },
  { code: 'ARS', symbol: '$', name: 'Argentine peso' },
  { code: 'AUD', symbol: '$', name: 'Australian dollar' },
  { code: 'AWG', symbol: '\u0192', name: 'Aruban florin' },
  { code: 'AZN', symbol: 'AZN', name: 'Azerbaijani manat' },
  { code: 'BAM', symbol: 'KM', name: 'Bosnia and Herzegovina konvertibilna marka' },
  { code: 'BBD', symbol: 'Bds$', name: 'Barbadian dollar' },
  { code: 'BDT', symbol: '\u09f3', name: 'Bangladeshi taka' },
  { code: 'BGN', symbol: 'BGN', name: 'Bulgarian lev' },
  { code: 'BHD', symbol: '.\u062f.\u0628', name: 'Bahraini dinar' },
  { code: 'BIF', symbol: 'FBu', name: 'Burundi franc' },
  { code: 'BMD', symbol: 'BD$', name: 'Bermudian dollar' },
  { code: 'BND', symbol: 'B$', name: 'Brunei dollar' },
  { code: 'BOB', symbol: 'Bs.', name: 'Bolivian boliviano' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian real' },
  { code: 'BSD', symbol: 'B$', name: 'Bahamian dollar' },
  { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese ngultrum' },
  { code: 'BWP', symbol: 'P', name: 'Botswana pula' },
  { code: 'BYR', symbol: 'Br', name: 'Belarusian ruble' },
  { code: 'BZD', symbol: 'BZ$', name: 'Belize dollar' },
  { code: 'CAD', symbol: '$', name: 'Canadian dollar' },
  { code: 'CDF', symbol: 'F', name: 'Congolese franc' },
  { code: 'CHF', symbol: 'Fr.', name: 'Swiss franc' },
  { code: 'CLP', symbol: '$', name: 'Chilean peso' },
  { code: 'CNY', symbol: '\u00a5', name: 'Chinese/Yuan renminbi' },
  { code: 'COP', symbol: 'Col$', name: 'Colombian peso' },
  { code: 'CRC', symbol: '\u20a1', name: 'Costa Rican colon' },
  { code: 'CUC', symbol: '$', name: 'Cuban peso' },
  { code: 'CVE', symbol: 'Esc', name: 'Cape Verdean escudo' },
  { code: 'CZK', symbol: 'K\u010d', name: 'Czech koruna' },
  { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian franc' },
  { code: 'DKK', symbol: 'Kr', name: 'Danish krone' },
  { code: 'DOP', symbol: 'RD$', name: 'Dominican peso' },
  { code: 'DZD', symbol: '\u062f.\u062c', name: 'Algerian dinar' },
  { code: 'EEK', symbol: 'KR', name: 'Estonian kroon' },
  { code: 'EGP', symbol: '\u00a3', name: 'Egyptian pound' },
  { code: 'ERN', symbol: 'Nfa', name: 'Eritrean nakfa' },
  { code: 'ETB', symbol: 'Br', name: 'Ethiopian birr' },
  { code: 'EUR', symbol: '\u20ac', name: 'European Euro' },
  { code: 'FJD', symbol: 'FJ$', name: 'Fijian dollar' },
  { code: 'FKP', symbol: '\u00a3', name: 'Falkland Islands pound' },
  { code: 'GBP', symbol: '\u00a3', name: 'British pound' },
  { code: 'GEL', symbol: 'GEL', name: 'Georgian lari' },
  { code: 'GHS', symbol: 'GH\u20b5', name: 'Ghanaian cedi' },
  { code: 'GIP', symbol: '\u00a3', name: 'Gibraltar pound' },
  { code: 'GMD', symbol: 'D', name: 'Gambian dalasi' },
  { code: 'GNF', symbol: 'FG', name: 'Guinean franc' },
  { code: 'GQE', symbol: 'CFA', name: 'Central African CFA franc' },
  { code: 'GTQ', symbol: 'Q', name: 'Guatemalan quetzal' },
  { code: 'GYD', symbol: 'GY$', name: 'Guyanese dollar' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong dollar' },
  { code: 'HNL', symbol: 'L', name: 'Honduran lempira' },
  { code: 'HRK', symbol: 'kn', name: 'Croatian kuna' },
  { code: 'HTG', symbol: 'G', name: 'Haitian gourde' },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian forint' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian rupiah' },
  { code: 'ILS', symbol: '\u20aa', name: 'Israeli new sheqel' },
  { code: 'INR', symbol: '\u20B9', name: 'Indian rupee' },
  { code: 'IQD', symbol: '\u062f.\u0639', name: 'Iraqi dinar' },
  { code: 'IRR', symbol: 'IRR', name: 'Iranian rial' },
  { code: 'ISK', symbol: 'kr', name: 'Icelandic kr\u00f3na' },
  { code: 'JMD', symbol: 'J$', name: 'Jamaican dollar' },
  { code: 'JOD', symbol: 'JOD', name: 'Jordanian dinar' },
  { code: 'JPY', symbol: '\u00a5', name: 'Japanese yen' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan shilling' },
  { code: 'KGS', symbol: '\u0441\u043e\u043c', name: 'Kyrgyzstani som' },
  { code: 'KHR', symbol: '\u17db', name: 'Cambodian riel' },
  { code: 'KMF', symbol: 'KMF', name: 'Comorian franc' },
  { code: 'KPW', symbol: 'W', name: 'North Korean won' },
  { code: 'KRW', symbol: 'W', name: 'South Korean won' },
  { code: 'KWD', symbol: 'KWD', name: 'Kuwaiti dinar' },
  { code: 'KYD', symbol: 'KY$', name: 'Cayman Islands dollar' },
  { code: 'KZT', symbol: 'T', name: 'Kazakhstani tenge' },
  { code: 'LAK', symbol: 'KN', name: 'Lao kip' },
  { code: 'LBP', symbol: '\u00a3', name: 'Lebanese lira' },
  { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan rupee' },
  { code: 'LRD', symbol: 'L$', name: 'Liberian dollar' },
  { code: 'LSL', symbol: 'M', name: 'Lesotho loti' },
  { code: 'LTL', symbol: 'Lt', name: 'Lithuanian litas' },
  { code: 'LVL', symbol: 'Ls', name: 'Latvian lats' },
  { code: 'LYD', symbol: 'LD', name: 'Libyan dinar' },
  { code: 'MAD', symbol: 'MAD', name: 'Morocodean dirham' },
  { code: 'MDL', symbol: 'MDL', name: 'Moldovan leu' },
  { code: 'MGA', symbol: 'FMG', name: 'Malagasy ariary' },
  { code: 'MKD', symbol: 'MKD', name: 'Macedonian denar' },
  { code: 'MMK', symbol: 'K', name: 'Myanma kyat' },
  { code: 'MNT', symbol: '\u20ae', name: 'Mongolian tugrik' },
  { code: 'MOP', symbol: 'P', name: 'Macanese pataca' },
  { code: 'MRO', symbol: 'UM', name: 'Mauritanian ouguiya' },
  { code: 'MUR', symbol: 'Rs', name: 'Mauritian rupee' },
  { code: 'MVR', symbol: 'Rf', name: 'Maldivian rufiyaa' },
  { code: 'MWK', symbol: 'MK', name: 'Malawian kwacha' },
  { code: 'MXN', symbol: '$', name: 'Mexican peso' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian ringgit' },
  { code: 'MZM', symbol: 'MTn', name: 'Mozambican metical' },
  { code: 'NAD', symbol: 'N$', name: 'Namibian dollar' },
  { code: 'NGN', symbol: '\u20a6', name: 'Nigerian naira' },
  { code: 'NIO', symbol: 'C$', name: 'Nicaraguan c\u00f3rdoba' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian krone' },
  { code: 'NPR', symbol: 'NRs', name: 'Nepalese rupee' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand dollar' },
  { code: 'OMR', symbol: 'OMR', name: 'Omani rial' },
  { code: 'PAB', symbol: 'B./', name: 'Panamanian balboa' },
  { code: 'PEN', symbol: 'S/.', name: 'Peruvian nuevo sol' },
  { code: 'PGK', symbol: 'K', name: 'Papua New Guinean kina' },
  { code: 'PHP', symbol: '\u20b1', name: 'Philippine peso' },
  { code: 'PKR', symbol: 'Rs.', name: 'Pakistani rupee' },
  { code: 'PLN', symbol: 'z\u0142', name: 'Polish zloty' },
  { code: 'PYG', symbol: '\u20b2', name: 'Paraguayan guarani' },
  { code: 'QAR', symbol: 'QR', name: 'Qatari riyal' },
  { code: 'RON', symbol: 'L', name: 'Romanian leu' },
  { code: 'RSD', symbol: 'din.', name: 'Serbian dinar' },
  { code: 'RUB', symbol: 'R', name: 'Russian ruble' },
  { code: 'SAR', symbol: 'SR', name: 'Saudi riyal' },
  { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands dollar' },
  { code: 'SCR', symbol: 'SR', name: 'Seychellois rupee' },
  { code: 'SDG', symbol: 'SDG', name: 'Sudanese pound' },
  { code: 'SEK', symbol: 'kr', name: 'Swedish krona' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore dollar' },
  { code: 'SHP', symbol: '\u00a3', name: 'Saint Helena pound' },
  { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean leone' },
  { code: 'SOS', symbol: 'Sh.', name: 'Somali shilling' },
  { code: 'SRD', symbol: '$', name: 'Surinamese dollar' },
  { code: 'SYP', symbol: 'LS', name: 'Syrian pound' },
  { code: 'SZL', symbol: 'E', name: 'Swazi lilangeni' },
  { code: 'THB', symbol: '\u0e3f', name: 'Thai baht' },
  { code: 'TJS', symbol: 'TJS', name: 'Tajikistani somoni' },
  { code: 'TMT', symbol: 'm', name: 'Turkmen manat' },
  { code: 'TND', symbol: 'DT', name: 'Tunisian dinar' },
  { code: 'TRY', symbol: 'TRY', name: 'Turkish new lira' },
  { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago dollar' },
  { code: 'TWD', symbol: 'NT$', name: 'New Taiwan dollar' },
  { code: 'TZS', symbol: 'TZS', name: 'Tanzanian shilling' },
  { code: 'UAH', symbol: 'UAH', name: 'Ukrainian hryvnia' },
  { code: 'UGX', symbol: 'USh', name: 'Ugandan shilling' },
  { code: 'USD', symbol: 'US$', name: 'United States dollar' },
  { code: 'UYU', symbol: '$U', name: 'Uruguayan peso' },
  { code: 'UZS', symbol: 'UZS', name: 'Uzbekistani som' },
  { code: 'VEB', symbol: 'Bs', name: 'Venezuelan bolivar' },
  { code: 'VND', symbol: '\u20ab', name: 'Vietnamese dong' },
  { code: 'VUV', symbol: 'VT', name: 'Vanuatu vatu' },
  { code: 'WST', symbol: 'WS$', name: 'Samoan tala' },
  { code: 'XAF', symbol: 'CFA', name: 'Central African CFA franc' },
  { code: 'XCD', symbol: 'EC$', name: 'East Caribbean dollar' },
  { code: 'XDR', symbol: 'SDR', name: 'Special Drawing Rights' },
  { code: 'XOF', symbol: 'CFA', name: 'West African CFA franc' },
  { code: 'XPF', symbol: 'F', name: 'CFP franc' },
  { code: 'YER', symbol: 'YER', name: 'Yemeni rial' },
  { code: 'ZAR', symbol: 'R', name: 'South African rand' },
  { code: 'ZMK', symbol: 'ZK', name: 'Zambian kwacha' },
  { code: 'ZWR', symbol: 'Z$', name: 'Zimbabwean dollar' }
];

const CurrencyList = [
  { key: 'INR', value: 'Indian Rupee - INR' },
  { key: 'USD', value: 'United States Dollar - USD' },
  { key: 'EUR', value: 'Euro - EUR' },
  { key: 'GBP', value: 'British Pound - GBP' },
  { key: 'AUD', value: 'Australian Dollar - AUD' },
  { key: 'CAD', value: 'Canadian Dollar - CAD' },
  { key: 'JPY', value: 'Japanese Yen - JPY' },
  { key: 'BYR', value: 'Belarusian Ruble - BYR' },
  { key: 'AED', value: 'United Arab Emirates Dirham - AED' },
  { key: 'AFN', value: 'Afghan Afghani - AFN' },
  { key: 'ALL', value: 'Albanian Lek - ALL' },
  { key: 'AMD', value: 'Armenian Dram - AMD' },
  { key: 'ANG', value: 'Netherlands Antillean Gulden - ANG' },
  { key: 'AOA', value: 'Angolan Kwanza - AOA' },
  { key: 'ARS', value: 'Argentine Peso - ARS' },
  { key: 'AWG', value: 'Aruban Florin - AWG' },
  { key: 'AZN', value: 'Azerbaijani Manat - AZN' },
  { key: 'BAM', value: 'Bosnia and Herzegovina Convertible Mark - BAM' },
  { key: 'BBD', value: 'Barbadian Dollar - BBD' },
  { key: 'BDT', value: 'Bangladeshi Taka - BDT' },
  { key: 'BGN', value: 'Bulgarian Lev - BGN' },
  { key: 'BHD', value: 'Bahraini Dinar - BHD' },
  { key: 'BIF', value: 'Burundian Franc - BIF' },
  { key: 'BMD', value: 'Bermudian Dollar - BMD' },
  { key: 'BND', value: 'Brunei Dollar - BND' },
  { key: 'BOB', value: 'Bolivian Boliviano - BOB' },
  { key: 'BRL', value: 'Brazilian Real - BRL' },
  { key: 'BSD', value: 'Bahamian Dollar - BSD' },
  { key: 'BTC', value: 'Bitcoin - BTC' },
  { key: 'BTN', value: 'Bhutanese Ngultrum - BTN' },
  { key: 'BWP', value: 'Botswana Pula - BWP' },
  { key: 'BYN', value: 'Belarusian Ruble - BYN' },
  { key: 'BZD', value: 'Belize Dollar - BZD' },
  { key: 'CDF', value: 'Congolese Franc - CDF' },
  { key: 'CHF', value: 'Swiss Franc - CHF' },
  { key: 'CLF', value: 'Unidad de Fomento - CLF' },
  { key: 'CLP', value: 'Chilean Peso - CLP' },
  { key: 'CNY', value: 'Chinese Renminbi Yuan - CNY' },
  { key: 'COP', value: 'Colombian Peso - COP' },
  { key: 'CRC', value: 'Costa Rican Colón - CRC' },
  { key: 'CUC', value: 'Cuban Convertible Peso - CUC' },
  { key: 'CUP', value: 'Cuban Peso - CUP' },
  { key: 'CVE', value: 'Cape Verdean Escudo - CVE' },
  { key: 'CZK', value: 'Czech Koruna - CZK' },
  { key: 'DJF', value: 'Djiboutian Franc - DJF' },
  { key: 'DKK', value: 'Danish Krone - DKK' },
  { key: 'DOP', value: 'Dominican Peso - DOP' },
  { key: 'DZD', value: 'Algerian Dinar - DZD' },
  { key: 'EEK', value: 'Estonian Kroon - EEK' },
  { key: 'EGP', value: 'Egyptian Pound - EGP' },
  { key: 'ERN', value: 'Eritrean Nakfa - ERN' },
  { key: 'ETB', value: 'Ethiopian Birr - ETB' },
  { key: 'FJD', value: 'Fijian Dollar - FJD' },
  { key: 'FKP', value: 'Falkland Pound - FKP' },
  { key: 'GBX', value: 'British Penny - GBX' },
  { key: 'GEL', value: 'Georgian Lari - GEL' },
  { key: 'GGP', value: 'Guernsey Pound - GGP' },
  { key: 'GHS', value: 'Ghanaian Cedi - GHS' },
  { key: 'GIP', value: 'Gibraltar Pound - GIP' },
  { key: 'GMD', value: 'Gambian Dalasi - GMD' },
  { key: 'GNF', value: 'Guinean Franc - GNF' },
  { key: 'GTQ', value: 'Guatemalan Quetzal - GTQ' },
  { key: 'GYD', value: 'Guyanese Dollar - GYD' },
  { key: 'HKD', value: 'Hong Kong Dollar - HKD' },
  { key: 'HNL', value: 'Honduran Lempira - HNL' },
  { key: 'HRK', value: 'Croatian Kuna - HRK' },
  { key: 'HTG', value: 'Haitian Gourde - HTG' },
  { key: 'HUF', value: 'Hungarian Forint - HUF' },
  { key: 'IDR', value: 'Indonesian Rupiah - IDR' },
  { key: 'ILS', value: 'Israeli New Sheqel - ILS' },
  { key: 'IMP', value: 'Isle of Man Pound - IMP' },
  { key: 'IQD', value: 'Iraqi Dinar - IQD' },
  { key: 'IRR', value: 'Iranian Rial - IRR' },
  { key: 'ISK', value: 'Icelandic Króna - ISK' },
  { key: 'JEP', value: 'Jersey Pound - JEP' },
  { key: 'JMD', value: 'Jamaican Dollar - JMD' },
  { key: 'JOD', value: 'Jordanian Dinar - JOD' },
  { key: 'KES', value: 'Kenyan Shilling - KES' },
  { key: 'KGS', value: 'Kyrgyzstani Som - KGS' },
  { key: 'KHR', value: 'Cambodian Riel - KHR' },
  { key: 'KMF', value: 'Comorian Franc - KMF' },
  { key: 'KPW', value: 'North Korean Won - KPW' },
  { key: 'KRW', value: 'South Korean Won - KRW' },
  { key: 'KWD', value: 'Kuwaiti Dinar - KWD' },
  { key: 'KYD', value: 'Cayman Islands Dollar - KYD' },
  { key: 'KZT', value: 'Kazakhstani Tenge - KZT' },
  { key: 'LAK', value: 'Lao Kip - LAK' },
  { key: 'LBP', value: 'Lebanese Pound - LBP' },
  { key: 'LKR', value: 'Sri Lankan Rupee - LKR' },
  { key: 'LRD', value: 'Liberian Dollar - LRD' },
  { key: 'LSL', value: 'Lesotho Loti - LSL' },
  { key: 'LTL', value: 'Lithuanian Litas - LTL' },
  { key: 'LVL', value: 'Latvian Lats - LVL' },
  { key: 'LYD', value: 'Libyan Dinar - LYD' },
  { key: 'MAD', value: 'Moroccan Dirham - MAD' },
  { key: 'MDL', value: 'Moldovan Leu - MDL' },
  { key: 'MGA', value: 'Malagasy Ariary - MGA' },
  { key: 'MKD', value: 'Macedonian Denar - MKD' },
  { key: 'MMK', value: 'Myanmar Kyat - MMK' },
  { key: 'MNT', value: 'Mongolian Tögrög - MNT' },
  { key: 'MOP', value: 'Macanese Pataca - MOP' },
  { key: 'MRO', value: 'Mauritanian Ouguiya - MRO' },
  { key: 'MTL', value: 'Maltese Lira - MTL' },
  { key: 'MUR', value: 'Mauritian Rupee - MUR' },
  { key: 'MVR', value: 'Maldivian Rufiyaa - MVR' },
  { key: 'MWK', value: 'Malawian Kwacha - MWK' },
  { key: 'MXN', value: 'Mexican Peso - MXN' },
  { key: 'MYR', value: 'Malaysian Ringgit - MYR' },
  { key: 'MZN', value: 'Mozambican Metical - MZN' },
  { key: 'NAD', value: 'Namibian Dollar - NAD' },
  { key: 'NGN', value: 'Nigerian Naira - NGN' },
  { key: 'NIO', value: 'Nicaraguan Córdoba - NIO' },
  { key: 'NOK', value: 'Norwegian Krone - NOK' },
  { key: 'NPR', value: 'Nepalese Rupee - NPR' },
  { key: 'NZD', value: 'New Zealand Dollar - NZD' },
  { key: 'OMR', value: 'Omani Rial - OMR' },
  { key: 'PAB', value: 'Panamanian Balboa - PAB' },
  { key: 'PEN', value: 'Peruvian Sol - PEN' },
  { key: 'PGK', value: 'Papua New Guinean Kina - PGK' },
  { key: 'PHP', value: 'Philippine Peso - PHP' },
  { key: 'PKR', value: 'Pakistani Rupee - PKR' },
  { key: 'PLN', value: 'Polish Złoty - PLN' },
  { key: 'PYG', value: 'Paraguayan Guaraní - PYG' },
  { key: 'QAR', value: 'Qatari Riyal - QAR' },
  { key: 'RON', value: 'Romanian Leu - RON' },
  { key: 'RSD', value: 'Serbian Dinar - RSD' },
  { key: 'RUB', value: 'Russian Ruble - RUB' },
  { key: 'RWF', value: 'Rwandan Franc - RWF' },
  { key: 'SAR', value: 'Saudi Riyal - SAR' },
  { key: 'SBD', value: 'Solomon Islands Dollar - SBD' },
  { key: 'SCR', value: 'Seychellois Rupee - SCR' },
  { key: 'SDG', value: 'Sudanese Pound - SDG' },
  { key: 'SEK', value: 'Swedish Krona - SEK' },
  { key: 'SGD', value: 'Singapore Dollar - SGD' },
  { key: 'SHP', value: 'Saint Helenian Pound - SHP' },
  { key: 'SKK', value: 'Slovak Koruna - SKK' },
  { key: 'SLL', value: 'Sierra Leonean Leone - SLL' },
  { key: 'SOS', value: 'Somali Shilling - SOS' },
  { key: 'SRD', value: 'Surinamese Dollar - SRD' },
  { key: 'SSP', value: 'South Sudanese Pound - SSP' },
  { key: 'STD', value: 'São Tomé and Príncipe Dobra - STD' },
  { key: 'SVC', value: 'Salvadoran Colón - SVC' },
  { key: 'SYP', value: 'Syrian Pound - SYP' },
  { key: 'SZL', value: 'Swazi Lilangeni - SZL' },
  { key: 'THB', value: 'Thai Baht - THB' },
  { key: 'TJS', value: 'Tajikistani Somoni - TJS' },
  { key: 'TMM', value: 'Turkmenistani Manat - TMM' },
  { key: 'TMT', value: 'Turkmenistani Manat - TMT' },
  { key: 'TND', value: 'Tunisian Dinar - TND' },
  { key: 'TOP', value: 'Tongan Paʻanga - TOP' },
  { key: 'TRY', value: 'Turkish Lira - TRY' },
  { key: 'TTD', value: 'Trinidad and Tobago Dollar - TTD' },
  { key: 'TWD', value: 'New Taiwan Dollar - TWD' },
  { key: 'TZS', value: 'Tanzanian Shilling - TZS' },
  { key: 'UAH', value: 'Ukrainian Hryvnia - UAH' },
  { key: 'UGX', value: 'Ugandan Shilling - UGX' },
  { key: 'UYU', value: 'Uruguayan Peso - UYU' },
  { key: 'UZS', value: 'Uzbekistan Som - UZS' },
  { key: 'VEF', value: 'Venezuelan Bolívar - VEF' },
  { key: 'VND', value: 'Vietnamese Đồng - VND' },
  { key: 'VUV', value: 'Vanuatu Vatu - VUV' },
  { key: 'WST', value: 'Samoan Tala - WST' },
  { key: 'XAF', value: 'Central African Cfa Franc - XAF' },
  { key: 'XAG', value: 'Silver (Troy Ounce) - XAG' },
  { key: 'XAU', value: 'Gold (Troy Ounce) - XAU' },
  { key: 'XBA', value: 'European Composite Unit - XBA' },
  { key: 'XBB', value: 'European Monetary Unit - XBB' },
  { key: 'XBC', value: 'European Unit of Account 9 - XBC' },
  { key: 'XBD', value: 'European Unit of Account 17 - XBD' },
  { key: 'XCD', value: 'East Caribbean Dollar - XCD' },
  { key: 'XDR', value: 'Special Drawing Rights - XDR' },
  { key: 'XFU', value: 'UIC Franc - XFU' },
  { key: 'XOF', value: 'West African Cfa Franc - XOF' },
  { key: 'XPD', value: 'Palladium - XPD' },
  { key: 'XPF', value: 'Cfp Franc - XPF' },
  { key: 'XPT', value: 'Platinum - XPT' },
  { key: 'YER', value: 'Yemeni Rial - YER' },
  { key: 'ZAR', value: 'South African Rand - ZAR' },
  { key: 'ZMK', value: 'Zambian Kwacha - ZMK' },
  { key: 'ZMW', value: 'Zambian Kwacha - ZMW' },
  { key: 'ZWD', value: 'Zimbabwean Dollar - ZWD' },
  { key: 'ZWL', value: 'Zimbabwean Dollar - ZWL' },
  { key: 'ZWN', value: 'Zimbabwean Dollar - ZWN' },
  { key: 'ZWR', value: 'Zimbabwean Dollar - ZWR' }
];

const CountyWithCode = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Åland Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'AndorrA', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Cote D'Ivoire", code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: "Korea, Democratic People'S Republic of", code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao People'S Democratic Republic", code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia, Federated States of', code: 'FM' },
  { name: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russian Federation', code: 'RU' },
  { name: 'RWANDA', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia and Montenegro', code: 'CS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' }
];

export { currencySymbols, CurrencyList, CountyWithCode, imageExportOptions, categoryList };
